FROM jlawton/ubuntu-dev:14.04
MAINTAINER Jim Lawton

RUN apt-get -y update

RUN apt-get -y install python
RUN apt-get -y install python-dev
RUN apt-get -y install python-pip

RUN pip install virtualenv
