FROM jlawton/ubuntu-dev
MAINTAINER Jim Lawton

RUN apt-get -y update

RUN apt-get -y install python
RUN apt-get -y install python-dev
RUN apt-get -y install python-pip
RUN apt-get -y install virtualenv
